title: Cryptokami
email: cryptokami@iohk.io
description: SL Documentation
baseurl: ""
url: "https://cryptokamidocs.com"
include: ["_pages","_docs"]
permalink: /:title

markdown: kramdown
highlighter: rouge
array: []
